apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-service-account
  namespace: saas-app
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: api-read-secrets-cluster-role
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: api-read-secrets-cluster-role-binding
subjects:
  - kind: ServiceAccount
    name: api-service-account
    namespace: saas-app
roleRef:
  kind: ClusterRole
  name: api-read-secrets-cluster-role
  apiGroup: rbac.authorization.k8s.io
