apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-service-account
  namespace: saas-app
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: api-cluster-role
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: api-cluster-role-binding
subjects:
  - kind: ServiceAccount
    name: api-service-account
    namespace: saas-app
roleRef:
  kind: ClusterRole
  name: api-cluster-role
  apiGroup: rbac.authorization.k8s.io
