apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: saas-poc
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/morettimaxi/qdrant-gitops'
    targetRevision: HEAD
    path: argo-cd/applications
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: saas-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
