apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: qdrant-client1
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/morettimaxi/qdrant-gitops.git
    path: argo-cd/clients/helm
    targetRevision: master
    helm:
      valueFiles:
        - client1/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: qdrant-client1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true  # Add this line to create the namespace automatically

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: qdrant-client2
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/morettimaxi/qdrant-gitops.git
    path: argo-cd/clients/helm
    targetRevision: master
    helm:
      valueFiles:
        - client2/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: qdrant-client2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true  # Add this line to create the namespace automatically
